# @Author: Dr. Jeffrey Chijioke-Uche, IBM Quantum Ambassador
# @last update: 2025-03-01
# @Description: This workflow is triggered on a schedule to check the quality of the software. 
#               This is to maintain the quality and fix any issues that may arise. This is quality Control.
# @ Reference:  This workflow ensures that all necessary checks are performed regularly to maintain software integrity. 

name: Force Sync - Periodic Quality Control
on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force sync all workflows'
        required: false
        default: 'false'

  push:
    branches: [ "pypi" ]


  schedule:
    - cron: '0 3 * * *'      
    - cron: '0 10 * * *'     
    - cron: '0 15 * * *'      
    - cron: '0 20 * * *'    
    - cron: '0 23 * * *'     
    - cron: '0 17 * * *'     
    - cron: '0 20 * * *'     
    - cron: '0 23 * * *'     
    - cron: '0 2 * * *'      
    - cron: '0 5 * * *'      
    - cron: '0 8 * * *'      
    - cron: '0 11 * * *'     
    - cron: '0 14 * * *'     
    - cron: '0 17 * * *'     
    - cron: '0 20 * * *'     
    - cron: '0 23 * * *'     
    - cron: '0 2 * * *'      

  workflow_run:
    workflows:
      - PyPI Deployment Environment
      - Qiskit Connector Quality Check
      - Python Compatibility
    types:
      - completed

permissions:
  actions: write
  contents: write
  deployments: write
  pull-requests: write
  checks: write
  statuses: write
  issues: write
  discussions: write
  pages: write
  packages: write

env:
  GPG_NAME_REAL: ${{ secrets.GPG_NAME_REAL }}
  GPG_NAME_EMAIL: ${{ secrets.GPG_NAME_EMAIL }}
  GPG_NAME_COMMENT: ${{ secrets.GPG_NAME_COMMENT }}
  GPG_GITHUB_OPERATOR: ${{ secrets.GPG_GITHUB_OPERATOR }}
  EXPECTED_GPG_KEY_ID: ${{ secrets.EXPECTED_GPG_KEY_ID }}
  UNAME_CONTRIBUTOR_09: ${{ secrets.UNAME_CONTRIBUTOR_09 }}
  UNAME_CONTRIBUTOR_03: ${{ secrets.UNAME_CONTRIBUTOR_03 }}
  EMAIL_CONTRIBUTOR_09: ${{ secrets.EMAIL_CONTRIBUTOR_09 }}
  EMAIL_CONTRIBUTOR_03: ${{ secrets.EMAIL_CONTRIBUTOR_03 }}

jobs:
  wait-and-dispatch:
    name: 🔄 Conditional Trigger of Release Sync Jobs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'

    steps:
      - name: 🔎 Ensure we're on main (scheduled run)
        if: github.event_name == 'schedule'
        run: |
          DEFAULT_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" https://api.github.com/repos/${{ github.repository }} | jq -r .default_branch)
          echo "🧠 Default branch is: $DEFAULT_BRANCH"
          if [ "$DEFAULT_BRANCH" != "main" ]; then
            echo "✅ Requirements is that the periodic workflow runs only from 'main' which is the source of truth."
            echo "✅ No job workflow was called. Thank you."
            exit 0
          fi


      - name: ⏳ Wait for all required workflows to complete successfully
        uses: ahmadnassri/action-workflow-queue@v1
        with:
          workflows: |
            PyPI Deployment Environment
            Qiskit Connector Quality Check
            Python Compatibility
          repo: ${{ github.repository }}
          token: ${{ secrets.PAT_GITHUB }}
          wait: true
          fail-fast: true
          required-status: completed


      #______________________________________________________________________________________________________
      #   --- Check if all workflows succeeded.
      #   --- If any workflow failed, exit with an error message.
      #______________________________________________________________________________________________________
      - name: ✅ All workflows succeeded — Dispatch Verify
        run: |
          echo "✅ All workflows succeeded."
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

      - name: Qiskit Connector Active State
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/pkg_active_check.py
          
      #______________________________________________________________________________________________________
      #   --- Check if all workflows succeeded.
      #   --- If any workflow failed, exit gracefully othrerwise continue.
      #   --- Dispatch the release-record.yml and coverage.yml workflows.
      #______________________________________________________________________________________________________
      - name: ✅ All workflows succeeded — Check for failures
        run: |
          if [ $? -ne 0 ]; then
            echo "[x] One or more workflows failed. Exiting."
            exit 0
          fi

      - name: ✅ All workflows succeeded — Dispatch release-record.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-record.yml
          token: ${{ secrets.PAT_GITHUB }}

      - name: ✅ All workflows succeeded — Dispatch coverage.yml
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: coverage.yml
          token: ${{ secrets.PAT_GITHUB }}

      #______________________________________________________________________________________________________
      #   --- Optional: Uncomment if you want to dispatch the release-tag.yml and release-id.yml workflows.
      #______________________________________________________________________________________________________
      # - name: ✅ All workflows succeeded — Dispatch release-tag.yml
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: release-tag.yml
      #     token: ${{ secrets.PAT_GITHUB }}

      # - name: ✅ All workflows succeeded — Dispatch release-id.yml
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: release-id.yml
      #     token: ${{ secrets.PAT_GITHUB }}
