# @Author: Dr. Jeffrey Chijioke-Uche, IBM Quantum Ambassador
# @last update: 2025-03-01

name: 🧠 Qcon Intelligent Core  - Sync PyPI Releases On-Dispatch

on:
  workflow_dispatch: 

permissions:
  contents: write
  actions: write
  deployments: write
  pull-requests: write
  checks: write
  statuses: write

env:
  GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_WORKFLOW: ${{ github.workflow }}
  
jobs:
  qcon-sync-entrypoint:
    name: 🧠 Qcon Sync Entrypoint
    runs-on: ubuntu-latest
    steps:
      - name: 🧠 Qcon Checkout repository
        uses: actions/checkout@v4

      - name: 🧠 Git Setup
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main

      - name: 🧠 Qiskit Connector Active State
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/pkg_active_check.py

      - name: 🧠 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

  qcon-sync-pypi:
    needs: qcon-sync-entrypoint
    name: 🧠 Qcon Sync PyPI releases to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: 🧠 Qcon Checkout repository
        uses: actions/checkout@v4

      - name: Sync PyPI releases to GitHub - Scriptorium
        id: sync-pypi-01
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/sync_pypi_releases.py

  qcon-dispatch:
    needs: qcon-sync-pypi
    name: 🧠 Qcon Sync PyPI releases to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: 🧠 Qcon Checkout repository
        uses: actions/checkout@v4

      #[D1]
      - name: 🧠 Qcon Dispatch Qcon Find and Sign Commit
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: qcon-fsc.yml
          token: ${{ secrets.PAT_GITHUB }}
      #[D2]
      - name: 🧠 Qcon Dispatch Qcon Find and Sign Tags
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: qcon-fst.yml
          token: ${{ secrets.PAT_GITHUB }}
      #[D3]
      - name: 🧠 Qcon Dispatch Qcon Intelligence Core - Release Manager
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: qcon-intelligence-core.yml
          token: ${{ secrets.PAT_GITHUB }}