# @Author: Dr. Jeffrey Chijioke-Uche, IBM Quantum Ambassador
# @last update: 2025-03-01

name: Sync PyPI Releases to GitHub

on:
  push:
    branches:
      - pypi
  workflow_dispatch: 
  schedule:
    - cron: '33 0 * * 6'   

permissions:
  contents: write
  actions: write
  deployments: write
  pull-requests: write
  checks: write
  statuses: write
  
jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Git Hard Reset Main
        run: |
          git fetch origin
          git checkout main
          git reset --hard origin/main

      - name: Qiskit Connector Active State
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/pkg_active_check.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Sync PyPI releases to GitHub
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/sync_pypi_releases.py
