# @Author: Dr. Jeffrey Chijioke-Uche, IBM Quantum Ambassador
# @last update: 2025-03-01

name: Sync PyPI Releases to GitHub

on:
  push:
    branches:
      - main
      # stable

  workflow_dispatch: # Required for external workflows to trigger this via API

permissions:
  contents: write
  actions: write
  deployments: write
  pull-requests: write
  checks: write
  statuses: write
  
jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Qiskit Connector Active State
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python tests/pkg_active_check.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Sync PyPI releases to GitHub
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        run: |
          python .github/scripts/sync_pypi_releases.py
