# @Author: Dr. Jeffrey Chijioke-Uche
# @Last Modified: 2025-05-10
# @Purpose: Automatically sign all unsigned GitHub release tags/commits using GPG and verified secret identity.
# @Signer: Dr. Jeffrey Chijioke-Uche
#_______________________________________________________________________________________________________________

name: 🧠 Qcon Intelligent Core - Sign Released Tags

on:
  push:
    branches: [pypi]
  workflow_dispatch: 
  schedule:
    - cron: '0 9 * * 0'  

permissions:
  contents: write
  actions: write
  deployments: write
  pull-requests: write
  checks: write
  statuses: write
  issues: write
  discussions: write
  pages: write
  packages: write
  security-events: write
  repository-projects: write

env:
  GPG_NAME_REAL: ${{ secrets.GPG_NAME_REAL }}
  GPG_NAME_EMAIL: ${{ secrets.GPG_NAME_EMAIL }}
  GPG_NAME_COMMENT: ${{ secrets.GPG_NAME_COMMENT }}
  GPG_GITHUB_OPERATOR: ${{ secrets.GPG_GITHUB_OPERATOR }}
  EXPECTED_GPG_KEY_ID: ${{ secrets.EXPECTED_GPG_KEY_ID }}
  UNAME_CONTRIBUTOR_09: ${{ secrets.UNAME_CONTRIBUTOR_09 }}
  UNAME_CONTRIBUTOR_03: ${{ secrets.UNAME_CONTRIBUTOR_03 }}
  EMAIL_CONTRIBUTOR_09: ${{ secrets.EMAIL_CONTRIBUTOR_09 }}
  EMAIL_CONTRIBUTOR_03: ${{ secrets.EMAIL_CONTRIBUTOR_03 }}

jobs:
  sign-release-tags:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Git Hard Reset Main
        run: |
          git reset --hard origin/main
          git pull origin main
    #____________________________________________________________________________________ 
    # This job is responsible for GPG key pair with GitHub.
    # It ensures that the GPG key is available for signing commits and tags.
    #____________________________________________________________________________________

      - name: Install jq (JSON processor)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch GitHub GPG Keys and Find Matching Key ID
        id: find_key
        run: |
          # EXPECTED_GPG_KEY_ID from secrets should be the 16-character GPG Key ID.
          echo "Searching for GPG key on GitHub with Key ID: $EXPECTED_GPG_KEY_ID"
          
          GPG_KEY_ID_MATCHED="" # Variable to store the matched API key_id
          key_found=false

          next_page_url="https://api.github.com/user/gpg_keys?per_page=100"

          while [[ -n "$next_page_url" ]]; do
              echo "Fetching GPG keys from: $next_page_url"
              header_file=$(mktemp)

              response_body=$(curl -s -L \
                                   -H "Authorization: token $GPG_GITHUB_OPERATOR" \
                                   -H "Accept: application/vnd.github+json" \
                                   -H "X-GitHub-Api-Version: 2022-11-28" \
                                   -D "$header_file" \
                                   "$next_page_url")
              curl_exit_status=$?

              if [ $curl_exit_status -ne 0 ]; then
                  echo "::error::Curl command failed with exit status $curl_exit_status for URL: $next_page_url"
                  rm -f "$header_file"
                  break
              fi

              if ! echo "$response_body" | jq -e '. | type == "array"' > /dev/null; then
                  echo "::warning::Response from $next_page_url was not a JSON array or was empty. Body: $response_body"
              fi

              # The API's 'key_id' field provides a 16-character ID.
              api_provided_key_ids=$(echo "$response_body" | jq -r '.[]? | .key_id // empty')

              if [[ -n "$api_provided_key_ids" ]]; then
                while IFS= read -r current_api_key_id; do # This is the 16-character ID from API
                    if [[ -z "$current_api_key_id" ]]; then
                        continue
                    fi
                    echo "Checking API provided key_id: $current_api_key_id"
                    
                    # Direct comparison: Does the API's 16-char key_id exactly match the 16-char EXPECTED_GPG_KEY_ID from secrets?
                    if [[ "$current_api_key_id" == "$EXPECTED_GPG_KEY_ID" ]]; then
                        echo "::notice::Match found! API Key ID '$current_api_key_id' matches Expected Key ID '$EXPECTED_GPG_KEY_ID'."
                        GPG_KEY_ID_MATCHED="$current_api_key_id"
                        key_found=true
                        break 2 # Exit both loops
                    fi
                done <<< "$api_provided_key_ids"
              fi

              link_header=$(grep -i '^Link:' "$header_file")
              if echo "$link_header" | grep -q 'rel="next"'; then
                  next_page_url=$(echo "$link_header" | sed -n 's/.*<\([^>]*\)>; rel="next".*/\1/p')
                  if [[ -z "$next_page_url" ]]; then
                      echo "::debug::'rel=\"next\"' found, but sed failed to extract URL. Link: $link_header"
                      next_page_url=""
                  fi
              else
                  next_page_url=""
              fi
              rm -f "$header_file"
          done

          if [[ "$key_found" == "true" ]]; then
            echo "Successfully matched API Key ID: $GPG_KEY_ID_MATCHED"
            echo "GPG_KEY_ID=$GPG_KEY_ID_MATCHED" >> $GITHUB_ENV
          else
            # This error message now clearly states what was being looked for.
            echo "::error::Expected GPG Key ID '$EXPECTED_GPG_KEY_ID' (from secrets) not found directly in any of the 'key_id' fields returned by the GitHub API after checking all pages."
            exit 1
          fi

      - name: Verify Found Key ID in Environment
        run: |
          if [[ -z "$GPG_KEY_ID" ]]; then
            echo "::error::GPG_KEY_ID environment variable was not set."
            exit 1
          else
            echo "Verified: GPG Key ID '$GPG_KEY_ID'."
            echo "GPG_KEY_ID is ready for use in subsequent GPG operations."
          fi

      - name: Import GPG Key, Configure Git, and Prepare for Signing
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "Setting GPG_TTY..."
          export GPG_TTY=$(tty)

          echo "Importing GPG key..."
          echo "${GPG_PASSPHRASE}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --import <(echo "${GPG_PRIVATE_KEY}")
          if [ $? -ne 0 ]; then
              echo "::error::GPG key import failed."
              exit 1
          fi
          echo "✅ GPG key imported."

          echo "Testing GPG key with a simple sign operation using GPG_KEY_ID: ${GPG_KEY_ID}"
          echo "test data" | echo "${GPG_PASSPHRASE}" | gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --clearsign --default-key "${GPG_KEY_ID}" > /dev/null
          if [ $? -ne 0 ]; then
              echo "::error::GPG sign test failed. Passphrase might not be available or key ID ('${GPG_KEY_ID}') is incorrect/ambiguous for GPG."
              exit 1
          fi
          echo "✅ GPG key test successful."

          echo "Configuring git with GPG key details..."
          git config --global user.name "$GPG_NAME_REAL"
          git config --global user.email "$GPG_NAME_EMAIL"
          git config --global user.signingkey "$GPG_KEY_ID" 
          git config --global commit.gpgsign true

          echo "✅ Git and GPG configured. Commits and tags will be signed using key."
      #__________________________________________________________________________________
   


      #____________________________________________________________________________________
      # This job is responsible for signing all unsigned release tags and commits.
      # It ensures that all tags and commits are properly signed with the GPG key.
      #____________________________________________________________________________________
      - name: 🏷️ Sign All Unsigned Release Tags
        run: |
          for tag in $(git tag --sort=creatordate); do
            echo "🔍 Checking tag: $tag"
            if ! git tag -v "$tag" 2>&1 | grep -q "Good signature"; then
              echo "🔄 Re-signing tag: $tag"
              commit_sha=$(git rev-list -n 1 "$tag")
              tag_message=$(git for-each-ref --format="%(contents)" refs/tags/$tag)

              git tag -d "$tag"
              GIT_COMMITTER_DATE="$(git show -s --format=%ci "$commit_sha")" \
              GIT_AUTHOR_DATE="$(git show -s --format=%ci "$commit_sha")" \
              git tag -s -u "$GPG_KEY_ID" "$tag" "$commit_sha" -m "$tag_message"
              echo "✅ Tag now signed with GPG key: $GPG_KEY_ID"
              echo "📤 Pushing signed tag to remote..."
              git push --force origin "$tag"
            else
              echo "✅ Tag $tag already signed. Skipping."
            fi
          done

      - name: 🖊️ Sign All Unsigned Commits
        run: |
          for commit in $(git rev-list --all); do
            if ! git verify-commit $commit &>/dev/null; then
              echo "🔄 Re-signing commit: $commit"
              GIT_COMMITTER_DATE="$(git show -s --format=%ci $commit)" \
              GIT_AUTHOR_DATE="$(git show -s --format=%ci $commit)" \
              GIT_AUTHOR_NAME="$GPG_NAME_REAL" \
              GIT_AUTHOR_EMAIL="$GPG_NAME_EMAIL" \
              GIT_COMMITTER_NAME="$GPG_NAME_REAL" \
              GIT_COMMITTER_EMAIL="$GPG_NAME_EMAIL" \

              git commit --amend --gpg-sign="$GPG_KEY_ID" --no-edit || true
              echo "✅ Now signed with GPG key: $GPG_KEY_ID"

              echo '📦 Fetching latest changes from remote...'
              git fetch origin

              echo '🔄 Check-1: Merging changes from remote main branch...'
              git merge origin/main --no-edit --allow-unrelated-histories || echo "⚠️ No unrelated histories to merge"

              echo "📤 Pushing signed commit to remote..."
              git push -f origin HEAD:${{ github.ref_name }}
            else
              echo "✅ Commit $commit already signed. Skipping."
            fi
          done

      #[D3]
      - name: 🧠 Dispatch Qcon Intelligence Core - Release Manager
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: qcon-intelligence-core.yml
          token: ${{ secrets.PAT_GITHUB }}